// Files a coding model must never write directly in a Unity project. Every rule says what
// to do instead, because a small model that is only told "no" tends to retry the same thing.

export type GuardRule = {
  id: string
  test: (projectPath: string) => boolean
  reason: string
}

const SERIALIZED_ASSETS =
  /\.(unity|prefab|asset|mat|controller|overridecontroller|anim|playable|physicmaterial|physicsmaterial2d|mixer|lighting|spriteatlas|preset|terrainlayer|shadergraph|shadersubgraph|vfx)$/

const GENERATED_DIRS = /^(library|temp|logs|obj|build|builds|usersettings|memorycaptures)\//

export const DEFAULT_RULES: GuardRule[] = [
  {
    id: "meta",
    test: (p) => p.endsWith(".meta"),
    reason:
      "Unity owns .meta files: it creates them itself and they hold the asset GUID that scenes and prefabs point to. Create or edit only the asset; the .meta appears when the Editor refreshes.",
  },
  {
    id: "generated",
    test: (p) => GENERATED_DIRS.test(p),
    reason: "This folder is generated by Unity and rebuilt at any time. Put code under Assets/ instead.",
  },
  {
    id: "project-files",
    test: (p) => !p.includes("/") && /\.(csproj|sln|slnx)$/.test(p),
    reason:
      "Unity regenerates .csproj/.sln files and discards manual changes. To reference another assembly edit the .asmdef; to add a package edit nothing and ask the user.",
  },
  {
    id: "serialized-asset",
    test: (p) => SERIALIZED_ASSETS.test(p),
    reason:
      "This is a Unity-serialized YAML asset: hand edits corrupt object references. For scenes use unity_scene_view to look, and unity_object_create, unity_object_modify, unity_component_add and unity_component_set to change things through the Editor. For other assets, tell the user what to change in the Editor. Do not write an Editor script just to build a scene.",
  },
  {
    id: "project-settings",
    test: (p) => p.startsWith("projectsettings/"),
    reason: "Project settings are changed from the Unity Editor. Tell the user which setting to change and why.",
  },
  {
    id: "package-manifest",
    test: (p) => p === "packages/manifest.json" || p === "packages/packages-lock.json",
    reason:
      "Packages are installed through the Unity Package Manager, which resolves versions for this Editor. Tell the user which package is needed instead of editing the manifest.",
  },
]

/** Comparison form: project-relative, forward slashes, lower case (Windows and macOS are case-insensitive). */
export function normalizeProjectPath(projectRelativePath: string): string {
  return projectRelativePath.replaceAll("\\", "/").replace(/^\.\//, "").toLowerCase()
}

export function checkWrite(projectRelativePath: string, allow: string[] = [], rules = DEFAULT_RULES): GuardRule | null {
  const normalized = normalizeProjectPath(projectRelativePath)
  if (normalized.startsWith("../")) return null
  return rules.find((rule) => !allow.includes(rule.id) && rule.test(normalized)) ?? null
}
